/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Represents info about order customer
 */
export class Customer extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email: string;

    /**
     * This field could be numeric string
     */
    @SpeakeasyMetadata()
    @Expose({ name: "erp_id" })
    erpId: number;

    @SpeakeasyMetadata()
    @Expose({ name: "first_name" })
    firstName: string;

    /**
     * This field could be numeric string
     */
    @SpeakeasyMetadata()
    @Expose({ name: "human_id" })
    humanId: number;

    /**
     * This field could be numeric string
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: number;

    @SpeakeasyMetadata()
    @Expose({ name: "last_name" })
    lastName: string;

    @SpeakeasyMetadata()
    @Expose({ name: "middle_name" })
    middleName: string;

    @SpeakeasyMetadata()
    @Expose({ name: "phone" })
    phone: string;
}
