/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Street } from "./street";
import { Expose, Type } from "class-transformer";

/**
 * Represents info about shipping via `Nova Posta PackStation` method
 */
export class NPPackStation extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "city" })
    city: string;

    @SpeakeasyMetadata()
    @Expose({ name: "city_id" })
    cityId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "comment" })
    comment: string;

    @SpeakeasyMetadata()
    @Expose({ name: "region" })
    region: string;

    @SpeakeasyMetadata()
    @Expose({ name: "region_id" })
    regionId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "settlement_description" })
    settlementDescription: string;

    @SpeakeasyMetadata()
    @Expose({ name: "settlement_type" })
    settlementType: string;

    /**
     * Represents info about street
     */
    @SpeakeasyMetadata()
    @Expose({ name: "street" })
    @Type(() => Street)
    street: Street;

    @SpeakeasyMetadata()
    @Expose({ name: "warehouse_id" })
    warehouseId: string;

    /**
     * This field could be numeric string
     */
    @SpeakeasyMetadata()
    @Expose({ name: "warehouse_number" })
    warehouseNumber: number;
}
