/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { OrderTicketStatus } from "./orderticketstatus";
import { Expose, Transform } from "class-transformer";

export class OrderTicket extends SpeakeasyBase {
    /**
     * Decision
     */
    @SpeakeasyMetadata()
    @Expose({ name: "decision" })
    decision: string;

    /**
     * Marketplace Order ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "order_id" })
    orderId: number;

    /**
     * Format YYYY-MM-DD[T]HH:MM
     */
    @SpeakeasyMetadata()
    @Expose({ name: "solution_time" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    solutionTime: Date;

    /**
     * Status
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: OrderTicketStatus;

    /**
     * BPM ticket ID
     */
    @SpeakeasyMetadata()
    @Expose({ name: "ticket_id" })
    ticketId: string;
}
