/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { OrderStatuses } from "./orderstatuses";
import { Expose } from "class-transformer";

/**
 * Represents info about new order status
 */
export class OrderStatus extends SpeakeasyBase {
    /**
     * This field could be numeric string
     */
    @SpeakeasyMetadata()
    @Expose({ name: "order_id" })
    orderId: number;

    /**
     * This field could be numeric string
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: OrderStatuses;
}
