/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { PaymentMethod } from "./paymentmethod";
import { PaymentStatus } from "./paymentstatus";
import { Expose } from "class-transformer";

/**
 * Represents info about order payment
 */
export class Payment extends SpeakeasyBase {
    /**
     * This field could be numeric string
     */
    @SpeakeasyMetadata()
    @Expose({ name: "method" })
    method: PaymentMethod;

    /**
     * This field could be numeric string
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: PaymentStatus;
}
