/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { NPPackStation } from "./nppackstation";
import { Recipient } from "./recipient";
import { Expose, Type } from "class-transformer";

export enum ShippingMethod {
    NovaposhtaPackstation = "novaposhta_packstation",
}

/**
 * Represents info about shipping order
 */
export class Shipping extends SpeakeasyBase {
    /**
     * Represents info about shipping via `Nova Posta PackStation` method
     */
    @SpeakeasyMetadata()
    @Expose({ name: "address" })
    @Type(() => NPPackStation)
    address: NPPackStation;

    @SpeakeasyMetadata()
    @Expose({ name: "method" })
    method: ShippingMethod;

    @SpeakeasyMetadata()
    @Expose({ name: "price" })
    price?: number;

    /**
     * Represents info about recipient
     */
    @SpeakeasyMetadata()
    @Expose({ name: "recipient" })
    @Type(() => Recipient)
    recipient: Recipient;
}
